from fastapi import FastAPI, Depends
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session

from agent import agent
import db_models
import settings

from database import engine, SessionLocal

from crud import (
    create_conversation,
    save_message,
    get_conversations,
    get_messages,
    delete_conversation,
    get_conversation_context
)

from schemas import ChatRequest

# -----------------------------
# Create Database Tables
# -----------------------------
db_models.Base.metadata.create_all(bind=engine)

app = FastAPI()

# -----------------------------
# Database Connection
# -----------------------------
def get_db():

    db = SessionLocal()

    try:
        yield db

    finally:
        db.close()

# -----------------------------
# CORS
# -----------------------------
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5175",
        "http://127.0.0.1:5175",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["X-Conversation-Id"],
)

# -----------------------------
# Home
# -----------------------------
@app.get("/")
def home():
    return {
        "message": "Workspace AI Backend Running"
    }


# ==================================================
# Get Recent Conversations
# ==================================================
@app.get("/conversations")
def conversations(
    db: Session = Depends(get_db)
):

    return get_conversations(db)


# ==================================================
# Load One Conversation
# ==================================================
@app.get("/conversation/{conversation_id}")
def conversation_history(
    conversation_id: int,
    db: Session = Depends(get_db)
):

    return get_messages(
        db,
        conversation_id
    )


# ==================================================
# Delete Conversation
# ==================================================
@app.delete("/conversation/{conversation_id}")
def delete_chat(
    conversation_id: int,
    db: Session = Depends(get_db)
):

    delete_conversation(
        db,
        conversation_id
    )

    return {
        "message": "Conversation Deleted"
    }


# ==================================================
# Chat
# ==================================================
@app.post("/chat")
def chat(
    request: ChatRequest,
    db: Session = Depends(get_db)
):

    conversation_id = request.conversation_id

    # Create New Conversation
    if conversation_id is None:

        conversation = create_conversation(
            db,
            request.message[:40]
        )

        conversation_id = conversation.id

    # Save User Message
    save_message(

        db,

        conversation_id,

        "User",

        request.message

    )

    def generate():
       #Get previous conversation messages
       conversation_history=get_conversation_context(
           db,
           conversation_id
       )
       #Add the current user message
       conversation_history=[
           {
           "role":"system",
           "content":settings.SYSTEM_PROMPT
       }
       ]+conversation_history
       
       full_response=""
       #stream agent messages
       for token,metadata in agent.stream(
           {
               "messages":conversation_history
           },
           config={
               "recursion_limit":5
           },
           stream_mode="messages"
       ):
           #only process text generated by the model
           if(
               metadata.get("langgraph_node")=="model"
               and token.content
           ):
               full_response+=token.content
               yield token.content
        # Save AI Message
       save_message(
            db,
            conversation_id,
            "AI",
            full_response

        )
    

    return StreamingResponse(
        generate(),
        media_type="text/plain",
        headers={
            "X-Conversation-Id": str(conversation_id)
        }
    )


 